pretrain: ./exp/ViT-B/32/8/model_best.pt
seed: 1024
data:
    dataset: kinetics-TPS
    modality: RGB
    num_segments: 8
    batch_size: 64
    workers: 8
    val_list: 'dataset/case_test.txt' # test_list.txt' #
    label_list: 'dataset/annotations/category_info.json'
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0
    emb_dropout: 0.0
    type: fm_clip
    sim_header: "meanP"   #Transf   meanP  LSTM  Conv_1D  Transf_cls
logging:
    eval_freq: 1
