resume:
pretrain:
seed: 1024
data:
    dataset: kinetics-TPS
    modality: RGB
    num_segments: 8
    batch_size: 64
    workers: 8
    train_list: 'dataset/train_list.txt'
    val_list: 'dataset/val_list.txt'
    label_list: 'dataset/annotations/category_info.json'
    input_size: 224
    randaug:
        N: 2
        M: 9
network:
    arch: RN50x64 #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0
    emb_dropout: 0.0
    type: fm_clip
    sim_header: "meanP"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 1.e-5
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    ratio: 1
    f_ratio: 10
logging:
    eval_freq: 1
