pretrain: ./exp/ViT-B/32/32/model_best.pt
seed: 1024
data:
    dataset: kinetics-TPS
    modality: RGB
    num_segments: 32
    seg_length: 1
    split: 1
    batch_size: 64
    workers: 16
    gpus: 4
    num_classes: 15
    image_tmpl: 'img_{:05d}.jpg'
    val_list: 'dataset/test_list.txt' #
    label_list: 'dataset/category_info.txt'
    index_bias: 1
    input_size: 224
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0
    emb_dropout: 0.0
    type: clip_ktps
    sim_header: "Transf"   #Transf   meanP  LSTM  Conv_1D  Transf_cls
    fix_text: False
    fix_img: False
    describe:
logging:
    print_freq: 10
    eval_freq: 1
